- hosts: all
  gather_facts: true
  pre_tasks:
    - set_fact:
        platform: debian
  roles:
    - role: "foo.rh"
      when: "'rh' == platform"
    - role: "foo.debian"
      when: "'debian' == platform"
    - role: "foo.ubuntu"
      when: "'ubuntu' == platform"
